### ISSUE TITLE
Update the admin code with admin web files

### ISSUE THREAD

**Issue by josephril** [dkashin/pipencoder-base#5]
Hello Dmitry,

Kindly update the repository frontend for node Admin control for accounts & adding Nodes.

if this a commercial license kindly ping me official email ID

**Comment by josephril** [comment]
Hello Dmitry,

Kindly update the repository frontend for node activation or provide some tip ti activate the same 

![image](https://user-images.githubusercontent.com/24975351/215804603-4cb09aa1-1f8f-4f3e-a712-f564e37ea47d.png)

**Comment by frankzan** [comment]
@josephril did you manage to fix the license issue ? Kindly ping me your official id for some help.

**Comment by josephril** [comment]
HELLO frankzan 

I have fixed  almost all issues and it works great working on improving the product cant share the build or help you in setup at the moment because i need to have written permission from Dmitry Kashin as the code not complete in the rep, i have added a few more lines to make it working .

**Comment by frankzan** [comment]
@josephril you went mute Sir. Whats the latest update Sir
